/**
 * TodoApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoItem } from './todoItem';

export interface GroupResponse { 
    id?: number;
    name?: string;
    isDefault?: boolean;
    modifiedDate?: Date;
    items?: Array<TodoItem>;
}