/**
 * TodoApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Priority = 'Low' | 'Medium' | 'High' | 'Urgent';

export const Priority = {
    Low: 'Low' as Priority,
    Medium: 'Medium' as Priority,
    High: 'High' as Priority,
    Urgent: 'Urgent' as Priority
};